stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the application..."

test_job:
  stage: test
  script:
    - echo "Running tests..."
    - bash validate.sh

deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
